print("saba nonashvili")

print("i")
print("did")
print("almost")
print("all")
print("the")
print("phisical")
print("work")
print("as")
print("home")
print("work")
print("i")
print("did")
print(75)
print("pushups")
print(150)
print("პრესი")
print(75)
print("squat")
print("i watched all of the videos")
print("they were very interesting")